platform :ios, '9.3'
use_frameworks!

abstract_target 'app' do
    
    
    target 'JGAlgorithms_Example'
    target 'JGAlgorithms-Swift'
    
    pod 'JGAlgorithms', :path => '../'

    target 'JGAlgorithms_Tests' do
        inherit! :search_paths
    end
    
    target 'JGAlgorithms-SwiftTests' do
        inherit! :search_paths
    end
end


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        target.build_configurations.each do |config|
#            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
#        end
#    end
#
#end
