platform :ios, '9.3'
use_frameworks!

abstract_target 'app' do
    pod 'JGAlgorithms', :path => '../'
    
    target 'JGAlgorithms_Example' do
        
    end
    target 'JGAlgorithms-Swift' do
        
    end

    target 'JGAlgorithms_Tests' do
        
    end
    
    target 'JGAlgorithms-SwiftTests' do
        
    end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
        end
    end

end
