# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8.2
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
script:
#1 - Test Obj-C example
- set -o pipefail && xcodebuild test -workspace Example/JGAlgorithms.xcworkspace -scheme JGAlgorithms-Example -destination 'id=AD8E8C76-910E-437D-88C2-4D6F6EBE3355' -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO | xcpretty
#2 - Test Swift example
- set -o pipefail && xcodebuild test -workspace Example/JGAlgorithms.xcworkspace -scheme JGAlgorithms-Swift -destination 'id=AD8E8C76-910E-437D-88C2-4D6F6EBE3355' -sdk iphonesimulator10.2 ONLY_ACTIVE_ARCH=NO | xcpretty
#3 - Lint library
- pod lib lint

addons:
    code_climate:
        repo_token: ba255c0753afa4f80a7f90e5a6d18a54299efa92d854e1aed7620f285a29ea2b